# Generated by Django 5.1.2 on 2025-05-31 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('time', models.CharField(max_length=20, verbose_name='乘车时间')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='运费金额')),
                ('payment_method', models.CharField(max_length=50, verbose_name='支付方式')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffbook_daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='司机')),
            ],
            options={
                'verbose_name': '乘务日报',
                'verbose_name_plural': '乘务日报',
                'ordering': ['-date'],
            },
        ),
    ]
