# Generated by Django 5.1.2 on 2025-06-16 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(blank=True, max_length=100, verbose_name='資格名')),
                ('qualification_number', models.CharField(blank=True, max_length=50, verbose_name='資格番号')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='交付日')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='staffbook.driver')),
            ],
            options={
                'verbose_name': '資格',
                'verbose_name_plural': '資格',
            },
        ),
    ]
