# Generated by Django 4.2.11 on 2025-08-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('edu', '学歴'), ('job', '職歴')], max_length=3)),
                ('driver_code', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=50)),
                ('start_year', models.PositiveIntegerField()),
                ('start_month', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_month', models.PositiveIntegerField(blank=True, null=True)),
                ('place', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='hire_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
