# Generated by Django 5.1.2 on 2025-06-01 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0002_driverdailyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(max_length=20, unique=True, verbose_name='员工コード')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('tax_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='税号')),
            ],
        ),
        migrations.RenameModel(
            old_name='DailySales',
            new_name='DriverDailySales',
        ),
        migrations.RenameModel(
            old_name='PayrollRecord',
            new_name='DriverPayrollRecord',
        ),
        migrations.RenameModel(
            old_name='ReportImage',
            new_name='DriverReportImage',
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
