# Generated by Django 4.2.11 on 2025-08-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0002_historyentry_driver_hire_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='hire_data',
            new_name='history_data',
        ),
    ]
