# Generated by Django 4.2.11 on 2025-08-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0003_rename_hire_data_driver_history_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='事業者名'),
        ),
        migrations.AddField(
            model_name='driver',
            name='workplace',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='営業所名'),
        ),
    ]
