# Generated by Django 5.1.2 on 2025-06-16 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0003_aptitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('reward_type', models.CharField(choices=[('reward', '奖励'), ('penalty', '惩罚')], max_length=20, verbose_name='类型')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='staffbook.driver', verbose_name='司机')),
            ],
            options={
                'verbose_name': '奖惩记录',
                'verbose_name_plural': '奖惩记录',
            },
        ),
    ]
