# Generated by Django 5.1.2 on 2025-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0003_driver_rename_dailysales_driverdailysales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreport',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='运费金额'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='乘车时间'),
        ),
    ]
