# Generated by Django 5.1.2 on 2025-06-01 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0004_alter_driverdailyreport_fare_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverpayrollrecord',
            options={'ordering': ['-month']},
        ),
        migrations.AlterModelOptions(
            name='driverreportimage',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='staffbook.driver', verbose_name='司机'),
        ),
        migrations.AlterField(
            model_name='driverdailysales',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='刷卡'),
        ),
        migrations.AlterField(
            model_name='driverdailysales',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='现金'),
        ),
        migrations.AlterField(
            model_name='driverdailysales',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='driverdailysales',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='staffbook.driver'),
        ),
        migrations.AlterField(
            model_name='driverdailysales',
            name='mileage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='里程'),
        ),
        migrations.AlterField(
            model_name='driverdailysales',
            name='ride_count',
            field=models.IntegerField(default=0, verbose_name='乘车次数'),
        ),
        migrations.AlterField(
            model_name='driverpayrollrecord',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='staffbook.driver'),
        ),
        migrations.AlterField(
            model_name='driverpayrollrecord',
            name='month',
            field=models.DateField(verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='driverpayrollrecord',
            name='note',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='driverpayrollrecord',
            name='salary_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实发工资'),
        ),
        migrations.AlterField(
            model_name='driverpayrollrecord',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总业绩'),
        ),
        migrations.AlterField(
            model_name='driverreportimage',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='driverreportimage',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_images', to='staffbook.driver'),
        ),
        migrations.AlterField(
            model_name='driverreportimage',
            name='image',
            field=models.ImageField(upload_to='report_images/', verbose_name='日报图片'),
        ),
        migrations.AlterField(
            model_name='driverreportimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterUniqueTogether(
            name='driverdailyreport',
            unique_together={('driver', 'date')},
        ),
    ]
