# Generated by Django 5.1.2 on 2025-06-16 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0004_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发放时间')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='staffbook.driver')),
            ],
            options={
                'verbose_name': '奖励记录',
                'verbose_name_plural': '奖励记录',
            },
        ),
        migrations.DeleteModel(
            name='Rewards',
        ),
    ]
