# Generated by Django 5.1.2 on 2025-06-02 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0005_alter_driverpayrollrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverdailyreport',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='time',
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='staffbook.driver'),
        ),
        migrations.CreateModel(
            name='DriverDailyReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='回数')),
                ('time', models.CharField(blank=True, max_length=20, null=True, verbose_name='乘车时间')),
                ('start_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='乘车地')),
                ('via', models.CharField(blank=True, max_length=100, null=True, verbose_name='経由')),
                ('end_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='降车地')),
                ('male_count', models.PositiveIntegerField(default=0, verbose_name='男')),
                ('female_count', models.PositiveIntegerField(default=0, verbose_name='女')),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='メータ料金')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付方式')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='staffbook.driverdailyreport')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
    ]
