# Generated by Django 5.1.2 on 2025-06-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0005_reward_delete_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='学校名称')),
                ('degree', models.CharField(blank=True, max_length=50, verbose_name='学位／学历')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='起始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='staffbook.driver')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
            },
        ),
    ]
