# Generated by Django 4.2.11 on 2025-10-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0003_alter_car_main_photo'),
        ('staffbook', '0005_drop_legacy_company_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('is_rest', models.BooleanField(default=False)),
                ('shift', models.CharField(blank=True, max_length=10)),
                ('any_car', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staffbook.driver')),
                ('first_choice_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_first_choice', to='carinfo.car')),
                ('second_choice_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_second_choice', to='carinfo.car')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
                'unique_together': {('driver', 'work_date')},
            },
        ),
    ]
