# Generated by Django 4.2.11 on 2025-10-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0003_alter_car_main_photo'),
        ('staffbook', '0006_driverschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverschedule',
            name='first_choice_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_first', to='carinfo.car'),
        ),
        migrations.AlterField(
            model_name='driverschedule',
            name='second_choice_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_second', to='carinfo.car'),
        ),
    ]
