# Generated by Django 5.1.2 on 2025-06-16 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0006_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverpayrollrecord',
            name='salary_paid',
        ),
        migrations.RemoveField(
            model_name='driverpayrollrecord',
            name='total_sales',
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='absence_days',
            field=models.IntegerField(default=0, verbose_name='欠勤日数'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='attendance_days',
            field=models.IntegerField(default=0, verbose_name='出勤日数'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基本給'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='資格手当'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='commute_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='通勤手当'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='early_minutes',
            field=models.IntegerField(default=0, verbose_name='早退分'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='employment_insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='雇用保険扣除'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='health_care_insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='介護保険'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='health_insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='健康保険扣除'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='holiday_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='休日手当'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='holiday_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='休日時間'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='holiday_work_days',
            field=models.IntegerField(default=0, verbose_name='休日出勤日数'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='income_tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='所得税扣除'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='late_minutes',
            field=models.IntegerField(default=0, verbose_name='遅刻分'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='差引支給額'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='night_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='深夜手当'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='深夜時間'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='役職手当'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他扣除'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='overtime_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='残業手当'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='残業時間'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='paid_leave_days',
            field=models.IntegerField(default=0, verbose_name='有給日数'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='pension_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='厚生年金扣除'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='resident_tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='住民税扣除'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='住宅手当'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='税金合計'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='総控除額'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='総支給額'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='total_working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='総労働時間'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='transportation_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='家族手当'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='workers_insurance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='労災保険扣除'),
        ),
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='working_days',
            field=models.IntegerField(default=0, verbose_name='就業日数'),
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_number', models.CharField(blank=True, max_length=32, verbose_name='年金番号')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='厚生年金加入日')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensions', to='staffbook.driver', verbose_name='司机')),
            ],
            options={
                'verbose_name': '厚生年金记录',
                'verbose_name_plural': '厚生年金记录',
            },
        ),
    ]
