# Generated by Django 5.1.2 on 2025-06-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0007_remove_driverpayrollrecord_salary_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='clock_in',
            field=models.TimeField(blank=True, null=True, verbose_name='出勤时间'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='clock_out',
            field=models.TimeField(blank=True, null=True, verbose_name='退勤时间'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, help_text='自动记录最后保存时间', null=True, verbose_name='编辑时间'),
        ),
    ]
