# Generated by Django 4.2.11 on 2025-11-01 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0003_alter_car_main_photo'),
        ('staffbook', '0007_alter_driverschedule_first_choice_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverschedule',
            name='admin_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='管理メモ'),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='assigned_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_assigned', to='carinfo.car', verbose_name='会社決定車両'),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='status',
            field=models.CharField(choices=[('pending', '未確定'), ('approved', '確定'), ('rejected', '差し戻し')], default='pending', max_length=16, verbose_name='ステータス'),
        ),
    ]
