# Generated by Django 5.1.2 on 2025-06-03 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0007_driver_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverdailyreport',
            options={'ordering': ['-date'], 'verbose_name': '乘务日报', 'verbose_name_plural': '乘务日报'},
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='运费金额'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='乘车时间'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='绑定用户'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='staffbook.driver', verbose_name='司机'),
        ),
        migrations.DeleteModel(
            name='DriverDailyReportItem',
        ),
    ]
