# Generated by Django 4.2.11 on 2025-11-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0008_driverschedule_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverschedule',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='割当日時'),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='assigned_by',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='割当方法'),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='assignment_meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='自動配車の理由'),
        ),
    ]
