# Generated by Django 5.1.2 on 2025-06-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0008_alter_driverdailyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': '司机资料', 'verbose_name_plural': '司机资料'},
        ),
        migrations.AlterModelOptions(
            name='driverdailysales',
            options={'ordering': ['-date'], 'verbose_name': '司机日销售', 'verbose_name_plural': '司机日销售'},
        ),
        migrations.AlterModelOptions(
            name='driverpayrollrecord',
            options={'ordering': ['-month'], 'verbose_name': '工资记录', 'verbose_name_plural': '工资记录'},
        ),
        migrations.AlterModelOptions(
            name='driverreportimage',
            options={'ordering': ['-date'], 'verbose_name': '日报图片', 'verbose_name_plural': '日报图片'},
        ),
    ]
