# Generated by Django 5.1.2 on 2025-06-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0008_driverdailyreport_clock_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
