# Generated by Django 5.1.2 on 2025-06-18 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0009_driverdailyreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='gas_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガソリン量 (L)'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='里程 (KM)'),
        ),
    ]
