# Generated by Django 4.2.11 on 2025-11-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0009_driverschedule_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='driverschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_car__isnull', False)), fields=('work_date', 'assigned_car'), name='uniq_car_per_day'),
        ),
    ]
