# Generated by Django 5.1.2 on 2025-06-04 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0009_alter_driver_options_alter_driverdailysales_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='time',
        ),
        migrations.CreateModel(
            name='DriverDailyReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_time', models.CharField(blank=True, max_length=30, verbose_name='乘车时间')),
                ('ride_from', models.CharField(blank=True, max_length=100, verbose_name='乘车地')),
                ('via', models.CharField(blank=True, max_length=100, verbose_name='経由')),
                ('ride_to', models.CharField(blank=True, max_length=100, verbose_name='降车地')),
                ('num_male', models.IntegerField(default=0, verbose_name='男')),
                ('num_female', models.IntegerField(default=0, verbose_name='女')),
                ('meter_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='メータ料金')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='支付方式')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='staffbook.driverdailyreport', verbose_name='所属日报')),
            ],
        ),
    ]
