# Generated by Django 5.1.2 on 2025-06-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0010_remove_driverdailyreport_fare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='payment_method',
            field=models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', '信用卡'), ('ticket', '乘车券'), ('barcode', '扫码(PayPay/AuPay/支付宝/微信Pay等)')], max_length=50, verbose_name='支付方式'),
        ),
    ]
