# Generated by Django 5.1.2 on 2025-06-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0010_driverdailyreport_gas_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='重点标记'),
        ),
    ]
