# Generated by Django 5.1.2 on 2025-06-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0011_driverdailyreportitem_is_flagged'),
        ('vehicles', '0023_delete_driverdailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='vehicles.vehicle', verbose_name='本日使用车辆'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='标记为重点'),
        ),
    ]
