# Generated by Django 4.2.11 on 2025-11-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0011_shift_aware_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='driverschedule',
            name='uniq_car_per_day',
        ),
    ]
