# Generated by Django 5.1.2 on 2025-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0012_alter_driverdailyreportitem_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '现金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', '信用卡'), ('ticket', '乘车券'), ('barcode', '扫码(PayPay/AuPay/支付宝/微信Pay等)')], max_length=16, verbose_name='支付方式'),
        ),
    ]
