# Generated by Django 5.1.2 on 2025-07-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0012_vehicle_driver_has_health_check_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': '员工资料', 'verbose_name_plural': '员工资料'},
        ),
        migrations.DeleteModel(
            name='DriverDailySales',
        ),
    ]
