# Generated by Django 5.1.2 on 2025-06-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0012_driverdailyreport_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='车辆名')),
                ('plate_number', models.CharField(max_length=20, verbose_name='车牌号')),
            ],
        ),
    ]
