# Generated by Django 5.1.2 on 2025-06-11 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0013_alter_driverdailyreportitem_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='编辑时间'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_dailyreports', to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
    ]
