# Generated by Django 5.1.2 on 2025-07-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0013_alter_driver_options_delete_driverdailysales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(max_length=20, unique=True, verbose_name='職員番号')),
                ('name', models.CharField(max_length=32, verbose_name='氏名')),
                ('department', models.CharField(blank=True, max_length=32, verbose_name='部門')),
                ('position', models.CharField(choices=[('事務', '事務'), ('経理', '経理'), ('管理者', '管理者'), ('その他', 'その他')], max_length=32, verbose_name='職種')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社年月日')),
                ('resigned_date', models.DateField(blank=True, null=True, verbose_name='退職日')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='電話番号')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='绑定用户')),
            ],
            options={
                'verbose_name': '事务员资料',
                'verbose_name_plural': '事务员资料',
            },
        ),
    ]
