# Generated by Django 5.1.2 on 2025-06-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0013_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジ'), ('barcode', '扫码'), ('cash', '現金(ながし)'), ('jingjiaoxin', '京交信'), ('omron', 'オムロン'), ('kyoto', '京都市他')], max_length=16, verbose_name='支付方式'),
        ),
    ]
