# Generated by Django 5.1.2 on 2025-06-22 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0014_alter_driverdailyreportitem_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='休憩時間',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=1200), null=True, verbose_name='休憩時間'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='勤務時間',
            field=models.DurationField(blank=True, null=True, verbose_name='勤務時間'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='実働時間',
            field=models.DurationField(blank=True, null=True, verbose_name='実働時間'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='残業時間',
            field=models.DurationField(blank=True, null=True, verbose_name='残業時間'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '現金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジットカード'), ('kyokushin', '京交信'), ('omron', 'オムロン'), ('kyotoshi', '京都市他'), ('qr', '扫码(PayPay/AuPay/支付宝/微信Pay等)')], max_length=16, verbose_name='支付方式'),
        ),
    ]
