# Generated by Django 5.1.2 on 2025-06-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0014_driverdailyreport_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=128, verbose_name='住址'),
        ),
        migrations.AddField(
            model_name='driver',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='出生年月日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.CharField(blank=True, max_length=40, verbose_name='公司名'),
        ),
        migrations.AddField(
            model_name='driver',
            name='education',
            field=models.CharField(blank=True, max_length=40, verbose_name='最终学历'),
        ),
        migrations.AddField(
            model_name='driver',
            name='employ_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='在职类型'),
        ),
        migrations.AddField(
            model_name='driver',
            name='family_info',
            field=models.TextField(blank=True, verbose_name='家族状况'),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=5, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='driver',
            name='health_check',
            field=models.CharField(blank=True, max_length=100, verbose_name='健康诊断结果'),
        ),
        migrations.AddField(
            model_name='driver',
            name='health_check_date',
            field=models.DateField(blank=True, null=True, verbose_name='健康诊断日期'),
        ),
        migrations.AddField(
            model_name='driver',
            name='health_insurance',
            field=models.CharField(blank=True, max_length=40, verbose_name='健康保险'),
        ),
        migrations.AddField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='聘用日期'),
        ),
        migrations.AddField(
            model_name='driver',
            name='note',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='driver',
            name='previous_employer',
            field=models.CharField(blank=True, max_length=40, verbose_name='前任勤务先'),
        ),
        migrations.AddField(
            model_name='driver',
            name='qualification',
            field=models.CharField(blank=True, max_length=40, verbose_name='资格证'),
        ),
        migrations.AddField(
            model_name='driver',
            name='qualification_date',
            field=models.DateField(blank=True, null=True, verbose_name='资格取得年月'),
        ),
        migrations.AddField(
            model_name='driver',
            name='workplace',
            field=models.CharField(blank=True, max_length=40, verbose_name='所属营业所'),
        ),
        migrations.CreateModel(
            name='DrivingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, max_length=30, verbose_name='车种')),
                ('years', models.IntegerField(blank=True, null=True, verbose_name='经验年数')),
                ('company', models.CharField(blank=True, max_length=50, verbose_name='经验公司')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_exp', to='staffbook.driver')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='家族姓名')),
                ('relation', models.CharField(max_length=10, verbose_name='关系')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='staffbook.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20, verbose_name='保险种类')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='加入年月日')),
                ('number', models.CharField(blank=True, max_length=40, verbose_name='保险号')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='staffbook.driver')),
            ],
        ),
    ]
