# Generated by Django 5.1.2 on 2025-07-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0014_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='report',
        ),
        migrations.AlterUniqueTogether(
            name='driverreportimage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='driverreportimage',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='driver',
        ),
        migrations.CreateModel(
            name='DriverInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20, verbose_name='保险种类')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='加入年月日')),
                ('number', models.CharField(blank=True, max_length=40, verbose_name='保险号')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_insurances', to='staffbook.driver')),
            ],
        ),
        migrations.DeleteModel(
            name='DriverDailyReport',
        ),
        migrations.DeleteModel(
            name='DriverDailyReportItem',
        ),
        migrations.DeleteModel(
            name='DriverReportImage',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
