# Generated by Django 5.1.2 on 2025-06-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0015_driverdailyreport_休憩時間_driverdailyreport_勤務時間_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='num_female',
            field=models.IntegerField(blank=True, null=True, verbose_name='女性'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='num_male',
            field=models.IntegerField(blank=True, null=True, verbose_name='男性'),
        ),
    ]
