# Generated by Django 5.1.2 on 2025-07-16 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0015_remove_driverdailyreportitem_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='入社年月日'),
            preserve_default=False,
        ),
    ]
