# Generated by Django 5.1.2 on 2025-06-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0015_driver_address_driver_birthday_driver_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='staff_code',
        ),
        migrations.AddField(
            model_name='driver',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='選任年月日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=2, verbose_name='血液型'),
        ),
        migrations.AddField(
            model_name='driver',
            name='create_date',
            field=models.DateField(blank=True, null=True, verbose_name='作成年月日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='department',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='従業員番号'),
        ),
        migrations.AddField(
            model_name='driver',
            name='kana',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='driver',
            name='position',
            field=models.CharField(blank=True, choices=[('1', '常時選任運転者'), ('2', '運転者'), ('3', '職員'), ('4', '整備士')], max_length=16, null=True, verbose_name='職種'),
        ),
        migrations.AddField(
            model_name='driver',
            name='remark',
            field=models.TextField(blank=True, verbose_name='特記事項'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='事業者名'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='employ_type',
            field=models.CharField(blank=True, choices=[('1', '正式運転者'), ('2', '非常勤運転者')], max_length=20, null=True, verbose_name='在职类型'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性')], max_length=1, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='入社年月日'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=30, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='workplace',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='営業所名'),
        ),
    ]
