# Generated by Django 5.1.2 on 2025-08-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0016_alter_driver_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayrollrecord',
            name='progressive_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='売上分段控除'),
        ),
    ]
