# Generated by Django 5.1.2 on 2025-06-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0016_remove_driver_birthday_remove_driver_staff_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
        migrations.AddField(
            model_name='driver',
            name='health_insurance_join_date',
            field=models.DateField(blank=True, null=True, verbose_name='健康保険加入日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='health_insurance_no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='健康保険番号'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo_date',
            field=models.DateField(blank=True, null=True, verbose_name='撮影年月日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], max_length=2, verbose_name='血液型'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.CharField(default='未設定', max_length=64, verbose_name='事業者名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='department',
            field=models.CharField(blank=True, default='未設定', max_length=32, verbose_name='部門'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_code',
            field=models.CharField(default='未設定', max_length=20, unique=True, verbose_name='従業員番号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='employ_type',
            field=models.CharField(choices=[('1', '正式運転者'), ('2', '非常勤運転者')], default='未設定', max_length=20, verbose_name='在职类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('M', '男性'), ('F', '女性')], default='未設定', max_length=1, verbose_name='性別'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='kana',
            field=models.CharField(default=1, max_length=32, verbose_name='フリガナ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(choices=[('1', '常時選任運転者'), ('2', '運転者'), ('3', '職員'), ('4', '整備士')], default='未設定', max_length=16, verbose_name='職種'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='workplace',
            field=models.CharField(default='未設定', max_length=64, verbose_name='営業所名'),
            preserve_default=False,
        ),
    ]
