# Generated by Django 5.1.2 on 2025-06-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0016_alter_driverdailyreportitem_num_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='deposit_amount',
            field=models.PositiveIntegerField(blank=True, help_text='手动输入的入金金额', null=True, verbose_name='入金額'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='deposit_difference',
            field=models.IntegerField(blank=True, help_text='入金 − 現金', null=True, verbose_name='過不足額'),
        ),
    ]
