# Generated by Django 5.1.2 on 2025-06-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0017_driverdailyreport_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='has_health_check',
            field=models.BooleanField(default=False, verbose_name='健康診断書提出済'),
        ),
        migrations.AddField(
            model_name='driver',
            name='has_license_copy',
            field=models.BooleanField(default=False, verbose_name='免許証コピー提出済'),
        ),
        migrations.AddField(
            model_name='driver',
            name='has_residence_certificate',
            field=models.BooleanField(default=False, verbose_name='住民票提出済'),
        ),
        migrations.AddField(
            model_name='driver',
            name='has_tax_form',
            field=models.BooleanField(default=False, verbose_name='扶養控除等申告書提出済'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_foreign',
            field=models.BooleanField(default=False, verbose_name='外国籍'),
        ),
        migrations.AddField(
            model_name='driver',
            name='nationality',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='国籍'),
        ),
        migrations.AddField(
            model_name='driver',
            name='residence_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='residence_cards/', verbose_name='在留カード画像'),
        ),
        migrations.AddField(
            model_name='driver',
            name='residence_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='在留期限'),
        ),
        migrations.AddField(
            model_name='driver',
            name='residence_status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='在留資格'),
        ),
        migrations.AddField(
            model_name='driver',
            name='work_permission_confirmed',
            field=models.BooleanField(default=False, verbose_name='就労資格確認済'),
        ),
    ]
