# Generated by Django 5.1.2 on 2025-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0017_remove_driver_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('M', '男性'), ('F', '女性')], max_length=4, verbose_name='性別'),
        ),
    ]
