# Generated by Django 5.1.2 on 2025-06-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0018_alter_driver_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='education',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='family_info',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='health_check',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='health_check_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='health_insurance',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='note',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='previous_employer',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='qualification_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='employment_insurance_join_date',
            field=models.DateField(blank=True, null=True, verbose_name='雇用保険加入日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='employment_insurance_no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='雇用保険番号'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pension_fund_join_date',
            field=models.DateField(blank=True, null=True, verbose_name='厚生年金基金加入日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pension_fund_no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='厚生年金基金番号'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pension_join_date',
            field=models.DateField(blank=True, null=True, verbose_name='厚生年金保険加入日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pension_no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='厚生年金保険番号'),
        ),
        migrations.AddField(
            model_name='driver',
            name='workers_insurance_join_date',
            field=models.DateField(blank=True, null=True, verbose_name='労災保険加入日'),
        ),
        migrations.AddField(
            model_name='driver',
            name='workers_insurance_no',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='労災保険番号'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='blood_type',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='血液型'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('未設定', '未設定')], default='未設定', max_length=8, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=32, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='特記事項'),
        ),
    ]
