# Generated by Django 5.1.2 on 2025-06-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0018_driver_has_health_check_driver_has_license_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='residence_status',
            field=models.CharField(blank=True, choices=[('日本人の配偶者等', '日本人の配偶者等'), ('永住者', '永住者'), ('定住者', '定住者'), ('家族滞在', '家族滞在'), ('技術・人文知識・国際業務', '技術・人文知識・国際業務'), ('技能', '技能'), ('技能実習', '技能実習'), ('特定技能46号', '特定技能46号'), ('留学', '留学'), ('研修', '研修'), ('短期滞在', '短期滞在'), ('その他', 'その他')], max_length=64, null=True, verbose_name='在留資格'),
        ),
    ]
