# Generated by Django 5.1.2 on 2025-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0019_remove_driver_education_remove_driver_family_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='position',
            field=models.CharField(choices=[('1', '常時選任運転者'), ('2', '運転者'), ('3', '職員'), ('4', '整備士')], max_length=32, verbose_name='職種'),
        ),
    ]
