# Generated by Django 5.1.2 on 2025-08-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0019_alter_company_id_alter_workplace_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='staffbook.company', verbose_name='事業者名'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='workplace',
            field=models.ForeignKey(db_column='workplace_id', on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='staffbook.workplace', verbose_name='営業所名'),
        ),
    ]
