# Generated by Django 5.1.2 on 2025-07-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0019_alter_driver_residence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='employ_type',
            field=models.CharField(choices=[('1', '正式運転者'), ('2', '非常勤運転者'), ('3', '退職者')], max_length=20, verbose_name='在職類型'),
        ),
    ]
