# Generated by Django 5.1.2 on 2025-06-11 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0020_alter_driver_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='种类')),
                ('label', models.CharField(blank=True, max_length=32, verbose_name='显示名')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='license_photos/', verbose_name='免许写真')),
                ('license_number', models.CharField(max_length=32, verbose_name='免許証番号')),
                ('issue_date', models.DateField(verbose_name='交付年月日')),
                ('expiry_date', models.DateField(verbose_name='有効期限')),
                ('date_acquired_a', models.DateField(blank=True, null=True, verbose_name='二・小・原取得年月日')),
                ('date_acquired_b', models.DateField(blank=True, null=True, verbose_name='其他取得年月日')),
                ('date_acquired_c', models.DateField(blank=True, null=True, verbose_name='二種取得年月日')),
                ('license_conditions', models.CharField(blank=True, max_length=128, verbose_name='条件')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='staffbook.driver')),
                ('license_types', models.ManyToManyField(blank=True, to='staffbook.licensetype', verbose_name='種\u3000類')),
            ],
        ),
    ]
