# Generated by Django 5.1.2 on 2025-07-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0020_alter_driver_employ_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='resigned_date',
            field=models.DateField(blank=True, null=True, verbose_name='退職日'),
        ),
    ]
