# Generated by Django 5.1.2 on 2025-07-03 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0005_car_body_shape_car_car_type_code_car_engine_model_and_more'),
        ('staffbook', '0021_driver_resigned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreport',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='carinfo.car', verbose_name='本日使用车辆'),
        ),
    ]
