# Generated by Django 5.1.2 on 2025-06-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0021_licensetype_driverlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='有効期限'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='交付年月日'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='license_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='免許証番号'),
        ),
    ]
