# Generated by Django 5.1.2 on 2025-06-14 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffbook', '0022_alter_driverlicense_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='has_issue',
            field=models.BooleanField(default=False, verbose_name='包含异常记录'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='comment',
            field=models.TextField(blank=True, verbose_name='录入员注释'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='has_issue',
            field=models.BooleanField(default=False, verbose_name='是否异常'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=4, null=True, verbose_name='血液型'),
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateField(verbose_name='发生日期')),
                ('description', models.CharField(max_length=100, verbose_name='简要说明')),
                ('penalty', models.CharField(blank=True, max_length=100, verbose_name='处理/处分')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='staffbook.driver', verbose_name='司机')),
            ],
            options={
                'verbose_name': '事故・違反',
                'verbose_name_plural': '事故・違反',
            },
        ),
    ]
