services:
  - type: web
    name: taxi-reservation
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn fleet_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false