services:
  - type: web
    name: taxi-reservation
    env: python
    plan: free
    # 在 build 里顺便收集一次静态文件
    buildCommand: |
      ./build.sh
      python manage.py collectstatic --noinput
    startCommand: "gunicorn fleet_project.wsgi:application"

    # —— 下面这两段用来把 staticfiles/ 和 media/ 分别挂到 /static 和 /media —— #
    staticPublishPath: staticfiles
    staticRoutes:
      - path: /static
        publishPath: staticfiles
      - path: /media
        publishPath: media

    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
