services:
  - type: web
    name: taxi-reservation
    env: python
    plan: free
    buildCommand: |
      ./build.sh
      python manage.py collectstatic --noinput
    startCommand: "gunicorn fleet_project.wsgi:application"

    # ✅ 仅保留 static 静态路径（media 改为用挂载磁盘）
    staticPublishPath: staticfiles
    staticRoutes:
      - path: /static
        publishPath: staticfiles

    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false

cronjobs:
  - name: auto-approve-reservations
    schedule: '*/10 * * * *'  # 每10分钟运行一次
    command: python manage.py auto_approve
