services:
  - type: web
    name: taxi-reservation
    runtime: python
    plan: free
    buildCommand: |
      ./build.sh
      python manage.py collectstatic --noinput
    preDeployCommand: |
      python manage.py migrate
    startCommand: gunicorn fleet_project.wsgi:application

    staticPublishPath: staticfiles
    staticRoutes:
      - path: /static
        publishPath: staticfiles

    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false

  - type: cron
    name: auto-approve-reservations
    runtime: python
    plan: starter         # cron 不支持 free
    buildCommand: |
      ./build.sh
    schedule: "*/10 * * * *"
    command: python manage.py auto_approve
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
