services:
  - type: web
    name: taxi-reservation-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    # 先跑 migrate，再收集静态文件
    preDeployCommand: "python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn fleet_project.wsgi:application"
    staticPublishPath: staticfiles
    autoDeploy: true