services:
  - type: web
    name: taxi-reservation-system
    env: python
    # 先安装依赖
    buildCommand: "pip install -r requirements.txt"
    # 部署前先执行 migrate 和 collectstatic
    preDeployCommand: "python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    startCommand: "gunicorn fleet_project.wsgi:application"
    staticPublishPath: staticfiles
    autoDeploy: true