services:
  - type: web
    name: taxi-reservation-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn fleet_project.wsgi:application"
    staticPublishPath: staticfiles
    autoDeploy: true
    preDeployCommand: "python manage.py collectstatic --noinput"
