services:
  - type: web
    name: taxi-reservation-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn fleet_project.wsgi:application --bind 0.0.0.0:8000"
    preDeployCommand: "python manage.py collectstatic --noinput"
    staticPublishPath: staticfiles
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11