# Generated by Django 5.1.2 on 2025-07-20 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkclicklog',
            name='link_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='linkclicklog',
            name='link_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='linkclicklog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
