# Generated by Django 5.1.2 on 2025-04-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveruser',
            name='is_formal',
            field=models.BooleanField(default=False, verbose_name='正社員'),
        ),
        migrations.AlterField(
            model_name='driveruser',
            name='is_temporary',
            field=models.BooleanField(default=False, verbose_name='アルバイト'),
        ),
    ]
