# Generated by Django 4.2.11 on 2025-11-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_dailyreport_admin',
            field=models.BooleanField(default=False, verbose_name='日报管理系统管理员'),
        ),
    ]
