# Generated by Django 5.1.2 on 2025-05-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_driveruser_is_formal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveruser',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='通知用メールアドレス'),
        ),
    ]
