# Generated by Django 5.1.2 on 2025-05-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_driveruser_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveruser',
            name='wants_notification',
            field=models.BooleanField(default=False, verbose_name='接收系统通知'),
        ),
    ]
