# Generated by Django 5.1.2 on 2025-06-09 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driveruser_wants_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dispatch_admin', models.BooleanField(default=False, verbose_name='配车系统管理员')),
                ('is_employee_admin', models.BooleanField(default=False, verbose_name='员工台账系统管理员')),
                ('is_vehicle_admin', models.BooleanField(default=False, verbose_name='车辆管理系统管理员')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
