# Generated by Django 5.1.2 on 2025-06-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_vehicle_admin',
            new_name='is_carinfo_admin',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_employee_admin',
            new_name='is_staffbook_admin',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_dispatch_admin',
            new_name='is_vehicles_admin',
        ),
    ]
