# Generated by Django 5.1.2 on 2025-07-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_is_vehicle_admin_userprofile_is_carinfo_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveruser',
            options={'verbose_name': '司机账户', 'verbose_name_plural': '司机账户'},
        ),
    ]
