# Generated by Django 5.1.2 on 2025-04-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('model', models.CharField(max_length=50, verbose_name='车型')),
                ('status', models.CharField(choices=[('available', '可预约'), ('reserved', '已预约'), ('out', '已出库'), ('maintenance', '维修中')], default='available', max_length=20, verbose_name='状态')),
            ],
        ),
    ]
