# Generated by Django 5.1.2 on 2025-07-03 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carinfo', '0005_car_body_shape_car_car_type_code_car_engine_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='轮播图链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图管理',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='提示内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '提示信息',
                'verbose_name_plural': '提示信息',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='用途说明')),
                ('status', models.CharField(choices=[('pending', '申请中'), ('reserved', '已预约'), ('out', '已出库'), ('canceled', '已取消'), ('completed', '已完成')], default='pending', max_length=10, verbose_name='状态')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='实际出库时间')),
                ('actual_return', models.DateTimeField(blank=True, null=True, verbose_name='实际入库时间')),
                ('approved', models.BooleanField(default=False, verbose_name='是否已审批')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by_system', models.BooleanField(default=False, verbose_name='是否系统自动审批')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='司机')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carinfo.car', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/%Y/%m/%d/', verbose_name='图片文件')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='carinfo.car', verbose_name='车辆')),
            ],
        ),
    ]
