# Generated by Django 5.1.2 on 2025-07-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_systemnotice_delete_carouselimage'),
    ]

    operations = [
    ]
