# Generated by Django 5.1.2 on 2025-07-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间（完整）'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间（完整）'),
        ),
    ]
