# Generated by Django 5.1.2 on 2025-04-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actual_departure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际出库时间'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_return',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际还车时间'),
        ),
    ]
