# Generated by Django 5.1.2 on 2025-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_reservation_actual_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', '申请中'), ('reserved', '已预约'), ('out', '已出库'), ('canceled', '已取消')], default='pending', max_length=10, verbose_name='状态'),
        ),
    ]
