# Generated by Django 5.1.2 on 2025-08-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_reservation_end_datetime_reservation_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('applying', '申请中'), ('booked', '已预约'), ('departed', '已出库'), ('completed', '已完成'), ('canceled', '决定不出库'), ('incomplete', '未完成出入库手续')], db_index=True, default='applying', max_length=20, verbose_name='状态'),
        ),
    ]
