# Generated by Django 5.1.2 on 2025-04-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='车检日期'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/', verbose_name='车辆照片'),
        ),
    ]
