# Generated by Django 5.1.2 on 2025-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_map_old_reservation_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', '申请中'), ('booked', '已预约'), ('out', '已出库'), ('done', '已完成'), ('cancel', '已取消'), ('incomplete', '未完成出入库手续')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
