# Generated by Django 5.1.2 on 2025-04-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_vehicle_options_reservation_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='轮播图片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图管理',
                'ordering': ['order'],
            },
        ),
    ]
