# Generated by Django 5.1.2 on 2025-04-20 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='结束日期'),
            preserve_default=False,
        ),
    ]
