# Generated by Django 5.1.2 on 2025-05-04 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_alter_reservation_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, verbose_name='用途说明'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('progress', models.FloatField(default=0.0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.task')),
            ],
        ),
    ]
