# Generated by Django 5.1.2 on 2025-05-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_remove_vehicle_photo_vehicleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='actual_return',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际入库时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', '申请中'), ('reserved', '已预约'), ('out', '已出库'), ('canceled', '已取消'), ('completed', '已完成')], default='pending', max_length=10, verbose_name='状态'),
        ),
    ]
