# Generated by Django 5.1.2 on 2025-05-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_alter_reservation_actual_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicle_photos/%Y/%m/%d/', verbose_name='车辆照片'),
        ),
    ]
