# Generated by Django 5.1.2 on 2025-05-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='image',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='轮播图链接'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='车辆图片链接'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
