# Generated by Django 5.1.2 on 2025-05-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_remove_carouselimage_image_remove_vehicleimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(default='', upload_to='vehicles/%Y/%m/%d/', verbose_name='图片文件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle', verbose_name='车辆'),
        ),
    ]
