# Generated by Django 5.1.2 on 2025-05-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_remove_vehicleimage_image_url_vehicleimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.URLField(verbose_name='图片文件'),
        ),
    ]
