# Generated by Django 5.1.2 on 2025-05-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicle_photos/', verbose_name='图片文件'),
        ),
    ]
