# Generated by Django 5.1.2 on 2025-05-28 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approval_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='是否已审批'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 28, 12, 23, 59, 188736, tzinfo=datetime.timezone.utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicles/%Y/%m/%d/', verbose_name='图片文件'),
        ),
    ]
