# Generated by Django 5.1.2 on 2025-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_reservation_approval_time_reservation_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved_by_system',
            field=models.BooleanField(default=False, verbose_name='是否系统自动审批'),
        ),
    ]
