# Generated by Django 5.1.2 on 2025-05-31 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_alter_reservation_options_alter_tip_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreport',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='司机'),
        ),
    ]
