# Generated by Django 5.1.2 on 2025-06-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_alter_driverdailyreport_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverDailyReport',
        ),
    ]
