# Generated by Django 5.1.2 on 2025-07-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0005_car_body_shape_car_car_type_code_car_engine_model_and_more'),
        ('vehicles', '0023_delete_driverdailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carinfo.car', verbose_name='车辆'),
        ),
    ]
