# Generated by Django 5.1.2 on 2025-07-03 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0005_car_body_shape_car_car_type_code_car_engine_model_and_more'),
        ('staffbook', '0022_alter_driverdailyreport_vehicle'),
        ('vehicles', '0024_alter_reservation_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='carinfo.car', verbose_name='车辆'),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
