# Generated by Django 4.2.11 on 2025-10-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '00xx_split_etc_burdens'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='etc_empty_charge_type',
            field=models.CharField(blank=True, choices=[('company', '会社負担'), ('driver', 'ドライバー立替'), ('customer', 'お客様支払')], default='', max_length=20, verbose_name='空車ETC負担'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='etc_riding_charge_type',
            field=models.CharField(blank=True, choices=[('company', '会社負担'), ('driver', 'ドライバー立替'), ('customer', 'お客様支払')], default='', max_length=20, verbose_name='乗車ETC負担'),
        ),
    ]
