# Generated by Django 5.1.2 on 2025-07-09 18:24

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carinfo', '0005_car_body_shape_car_car_type_code_car_engine_model_and_more'),
        ('staffbook', '0015_remove_driverdailyreportitem_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('has_issue', models.BooleanField(default=False, verbose_name='包含异常记录')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('clock_in', models.TimeField(blank=True, null=True, verbose_name='出勤时间')),
                ('clock_out', models.TimeField(blank=True, null=True, verbose_name='退勤时间')),
                ('勤務時間', models.DurationField(blank=True, null=True, verbose_name='勤務時間')),
                ('休憩時間', models.DurationField(blank=True, default=datetime.timedelta(seconds=1200), null=True, verbose_name='休憩時間')),
                ('実働時間', models.DurationField(blank=True, null=True, verbose_name='実働時間')),
                ('残業時間', models.DurationField(blank=True, null=True, verbose_name='残業時間')),
                ('deposit_amount', models.PositiveIntegerField(blank=True, help_text='手动输入的入金金额', null=True, verbose_name='入金額')),
                ('deposit_difference', models.IntegerField(blank=True, help_text='入金 − 現金', null=True, verbose_name='過不足額')),
                ('gas_volume', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガソリン量 (L)')),
                ('mileage', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='里程 (KM)')),
                ('edited_at', models.DateTimeField(auto_now=True, help_text='自动记录最后保存时间', null=True, verbose_name='编辑时间')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='staffbook.driver', verbose_name='司机')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_dailyreports', to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to='carinfo.car', verbose_name='本日使用车辆')),
            ],
            options={
                'verbose_name': '乘务日报',
                'verbose_name_plural': '乘务日报',
                'ordering': ['-date'],
                'unique_together': {('driver', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DriverDailyReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_time', models.CharField(blank=True, max_length=30, verbose_name='乘车时间')),
                ('ride_from', models.CharField(blank=True, max_length=100, verbose_name='乘车地')),
                ('via', models.CharField(blank=True, max_length=100, verbose_name='経由')),
                ('ride_to', models.CharField(blank=True, max_length=100, verbose_name='降车地')),
                ('num_male', models.IntegerField(blank=True, null=True, verbose_name='男性')),
                ('num_female', models.IntegerField(blank=True, null=True, verbose_name='女性')),
                ('meter_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='メータ料金')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '现金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジットカード'), ('ticket', 'チケット'), ('qr', 'バーコード'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他')], max_length=16, verbose_name='支付方式')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('comment', models.TextField(blank=True, verbose_name='录入员注释')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='标记为重点')),
                ('has_issue', models.BooleanField(default=False, verbose_name='是否异常')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dailyreport.driverdailyreport', verbose_name='所属日报')),
            ],
        ),
        migrations.CreateModel(
            name='DriverReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('image', models.ImageField(upload_to='report_images/', verbose_name='日报图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_images', to='staffbook.driver')),
            ],
            options={
                'verbose_name': '日报图片',
                'verbose_name_plural': '日报图片',
                'ordering': ['-date'],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
