# Generated by Django 4.2.11 on 2025-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='driverdailyreportsegment',
            constraint=models.UniqueConstraint(fields=('report', 'vehicle', 'start_time', 'end_time'), name='uniq_report_vehicle_start_end'),
        ),
    ]
