# Generated by Django 4.2.11 on 2025-08-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0001_initial'),
        ('dailyreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDailyReportSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='dailyreport.driverdailyreport')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carinfo.car')),
            ],
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='dailyreport.driverdailyreportsegment', verbose_name='所属车辆分段'),
        ),
    ]
