# Generated by Django 4.2.11 on 2025-08-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_driverdailyreportsegment_uniq_report_vehicle_start_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='segment',
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='is_pending',
            field=models.BooleanField(default=False, verbose_name='待入'),
        ),
        migrations.DeleteModel(
            name='DriverDailyReportSegment',
        ),
    ]
