# Generated by Django 4.2.11 on 2025-10-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_alter_driverdailyreportitem_etc_empty_charge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_empty_card',
            field=models.CharField(blank=True, choices=[('company', '会社カード'), ('driver', '自己カード')], default='company', max_length=16, verbose_name='空車ETC カード'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_rider_payer',
            field=models.CharField(choices=[('company', '会社カード'), ('driver', '自己カード'), ('customer', 'お客様カード')], default='company', max_length=16, verbose_name='乗車ETC の支払者'),
        ),
    ]
