# Generated by Django 5.1.2 on 2025-07-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_alter_driverdailyreportitem_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_collected',
            field=models.PositiveIntegerField(blank=True, help_text='司机当天实际收回的 ETC 金额', null=True, verbose_name='ETC实际收取'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_expected',
            field=models.PositiveIntegerField(blank=True, help_text='ETC 由公司支付后，司机应向乘客收回的总额', null=True, verbose_name='ETC应收合计'),
        ),
    ]
