# Generated by Django 5.1.2 on 2025-07-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0003_driverdailyreport_etc_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_collected_app',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='司机通过app录入的ETC金额', null=True, verbose_name='ETC app收'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_collected_cash',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='司机从乘客处现金收取的ETC金额', null=True, verbose_name='ETC现金收'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_collected',
            field=models.PositiveIntegerField(blank=True, help_text='司机当天实际收回的 ETC 金额（旧字段，可废弃）', null=True, verbose_name='ETC实际收取'),
        ),
    ]
