# Generated by Django 4.2.11 on 2025-09-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0003_remove_driverdailyreportitem_segment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_payment_method',
            field=models.CharField(blank=True, choices=[('cash', '現金'), ('uber_cash', 'Uber（現金）'), ('uber', 'Uber'), ('uber_reservation', 'Uber予約'), ('uber_tip', 'Uberチップ'), ('uber_promotion', 'Uberプロモーション'), ('didi_cash', 'Didi（現金）'), ('didi', 'Didi'), ('go_cash', 'GO（現金）'), ('go', 'GO'), ('credit_card', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他')], max_length=20, null=True, verbose_name='ETC收取方式'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '現金'), ('uber_cash', 'Uber（現金）'), ('uber', 'Uber'), ('uber_reservation', 'Uber予約'), ('uber_tip', 'Uberチップ'), ('uber_promotion', 'Uberプロモーション'), ('didi_cash', 'Didi（現金）'), ('didi', 'Didi'), ('go_cash', 'GO（現金）'), ('go', 'GO'), ('credit_card', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他')], max_length=16, verbose_name='支付方式'),
        ),
    ]
