# Generated by Django 4.2.11 on 2025-11-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0004_auto_20251020_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_driver_cost',
            field=models.PositiveIntegerField(default=0, help_text='会社カード等で支払ったETCのうち、ドライバー負担とする金額の合計', verbose_name='司机負担ETC（給与控除）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_empty_card',
            field=models.CharField(blank=True, choices=[('company', '会社カード'), ('own', '自己カード')], default='company', max_length=16, verbose_name='空車ETC カード'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_rider_payer',
            field=models.CharField(choices=[('company', '会社カード'), ('own', '自己カード'), ('customer', 'お客様カード')], default='company', max_length=16, verbose_name='乗車ETC の支払者'),
        ),
    ]
