# Generated by Django 4.2.11 on 2025-10-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0004_alter_driverdailyreport_etc_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='etc_charge_type',
            field=models.CharField(choices=[('company', '会社負担'), ('driver', 'ドライバー立替'), ('customer', 'お客様支払')], default='company', max_length=20, verbose_name='ETC負担'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='etc_empty',
            field=models.PositiveIntegerField(default=0, verbose_name='空車ETC（円）'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='etc_riding',
            field=models.PositiveIntegerField(default=0, verbose_name='乗車ETC（円）'),
        ),
    ]
