# Generated by Django 5.1.2 on 2025-07-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0004_driverdailyreport_etc_collected_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='etc_collected',
        ),
    ]
