# Generated by Django 5.1.2 on 2025-07-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0005_remove_driverdailyreport_etc_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='etc_collected_app',
        ),
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='etc_collected_cash',
        ),
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='etc_expected',
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_collected',
            field=models.PositiveIntegerField(blank=True, help_text='日计账单中“空乘合计”', null=True, verbose_name='ETC收取金额（円）'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_payment_method',
            field=models.CharField(blank=True, choices=[('cash', '现金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他')], max_length=20, null=True, verbose_name='ETC收取方式'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_uncollected',
            field=models.PositiveIntegerField(blank=True, help_text='日计账单中“空车合计”', null=True, verbose_name='ETC未收金额（円）'),
        ),
    ]
