# Generated by Django 4.2.11 on 2025-10-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0005_driverdailyreportitem_etc_charge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_rider_payer',
            field=models.CharField(choices=[('company', '会社カード'), ('own', '自己カード'), ('customer', 'お客様カード')], default='company', max_length=16, verbose_name='乗車ETC の支払者'),
        ),
    ]
