# Generated by Django 4.2.11 on 2025-11-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0005_driverdailyreport_etc_driver_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_return_fee_claimed',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='回程費として客側から受け取った金額', null=True, verbose_name='回程費 受領額（円）'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_return_fee_method',
            field=models.CharField(blank=True, choices=[('none', '— 個別（別払い/なし）—'), ('app_ticket', 'アプリ/チケット 一体結算'), ('cash_to_driver', '現金（直接司机）')], default='none', max_length=16, verbose_name='回程費 支払方法'),
        ),
    ]
