# Generated by Django 4.2.11 on 2025-10-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0006_driverdailyreport_etc_rider_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_empty_card',
            field=models.CharField(blank=True, choices=[('company', '会社カード'), ('own', '自己カード')], default='company', max_length=16, verbose_name='空車ETC カード'),
        ),
    ]
