# Generated by Django 5.1.2 on 2025-07-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0006_remove_driverdailyreport_etc_collected_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_collected_app',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ETCアプリ収取（円）'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_collected_cash',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ETC現金收取（円）'),
        ),
    ]
