# Generated by Django 4.2.11 on 2025-11-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0006_driverdailyreport_etc_return_fee_claimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_collected',
            field=models.PositiveIntegerField(blank=True, help_text='日计账单中“空乘合计”（乗車ETC の実際收取額）', null=True, verbose_name='ETC收取金额（円）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_driver_cost',
            field=models.PositiveIntegerField(default=0, help_text='会社カード/自己カード等复杂情况最终认定为“司机自费”的ETC金额合计（工资扣除对象）', verbose_name='司机負担ETC（給与控除）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_return_fee_claimed',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='回程費として客側から受け取った金額（アプリ一体／現金等）', null=True, verbose_name='回程費 受領額（円）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_shortage',
            field=models.PositiveIntegerField(default=0, help_text='ETC应收合计 − 实际收取合计 的不足部分，仅用于统计/提示，不直接从工资中扣除。', verbose_name='ETC不足额'),
        ),
    ]
