# Generated by Django 4.2.11 on 2025-11-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0007_alter_driverdailyreport_etc_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='etc_charge_type',
            field=models.CharField(blank=True, choices=[('company', '会社負担'), ('driver', 'ドライバー立替'), ('customer', 'お客様支払')], default='company', max_length=20, null=True, verbose_name='ETC負担'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='etc_empty_charge_type',
            field=models.CharField(blank=True, choices=[('company', '会社負担'), ('driver', 'ドライバー立替'), ('customer', 'お客様支払')], default='company', max_length=20, null=True, verbose_name='空車ETC負担'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='etc_riding_charge_type',
            field=models.CharField(blank=True, choices=[('company', '会社負担'), ('driver', 'ドライバー立替'), ('customer', 'お客様支払')], default='company', max_length=20, null=True, verbose_name='乗車ETC負担'),
        ),
    ]
