# Generated by Django 4.2.11 on 2025-11-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0008_alter_driverdailyreportitem_etc_charge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='etc_empty',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='空車ETC（円）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='etc_riding',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='乗車ETC（円）'),
        ),
    ]
