# Generated by Django 5.1.2 on 2025-07-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0008_driverdailyreportitem_is_charter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='combined_group',
            field=models.CharField(blank=True, help_text='用于标记多个支付方式属于同一单', max_length=20, null=True, verbose_name='合算组编号'),
        ),
    ]
