# Generated by Django 5.1.2 on 2025-07-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0009_driverdailyreportitem_combined_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='combined_group',
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='ETC备注'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='etc_shortage',
            field=models.PositiveIntegerField(default=0, help_text='ETC使用金额超过应收金额的部分，将从工资中扣除', verbose_name='ETC不足额'),
        ),
    ]
