# Generated by Django 4.2.11 on 2025-12-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0009_alter_driverdailyreportitem_etc_empty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='advance_amount',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='司机为公司应急购买物品等的垫付金额（不计入売上/入金）', verbose_name='立替金額（円）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_payment_method',
            field=models.CharField(blank=True, choices=[('cash', '現金'), ('uber_cash', 'Uber（現金）'), ('uber', 'Uber'), ('uber_reservation', 'Uber予約'), ('uber_tip', 'Uberチップ'), ('uber_promotion', 'Uberプロモーション'), ('didi_cash', 'Didi（現金）'), ('didi', 'Didi'), ('go_cash', 'GO（現金）'), ('go', 'GO'), ('credit_card', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他'), ('advance', '立替（会社用）')], max_length=20, null=True, verbose_name='ETC收取方式'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '現金'), ('uber_cash', 'Uber（現金）'), ('uber', 'Uber'), ('uber_reservation', 'Uber予約'), ('uber_tip', 'Uberチップ'), ('uber_promotion', 'Uberプロモーション'), ('didi_cash', 'Didi（現金）'), ('didi', 'Didi'), ('go_cash', 'GO（現金）'), ('go', 'GO'), ('credit_card', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他'), ('advance', '立替（会社用）')], max_length=16, verbose_name='支付方式'),
        ),
    ]
