# Generated by Django 5.1.2 on 2025-07-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0010_remove_driverdailyreportitem_combined_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='combined_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='合算グループ'),
        ),
    ]
