# Generated by Django 4.2.11 on 2025-12-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0010_driverdailyreportitem_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='payroll_bd_advance',
            field=models.IntegerField(default=0, verbose_name='給与内訳：立替返還'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='payroll_bd_etc_refund',
            field=models.IntegerField(default=0, verbose_name='給与内訳：ETC返還（会社→運転手）'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='payroll_bd_over_short_to_company',
            field=models.IntegerField(default=0, help_text='参考表示用（給与合計には含めない）。', verbose_name='給与内訳：精算（運転手→会社、給与に含めない）'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='payroll_bd_over_short_to_driver',
            field=models.IntegerField(default=0, verbose_name='給与内訳：精算補填（会社→運転手）'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='payroll_bd_sales',
            field=models.IntegerField(default=0, verbose_name='給与内訳：売上'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='payroll_total',
            field=models.IntegerField(default=0, help_text='編集画面で算出した日次の給与合計（表示専用）。月次はこの合計値を加算して表示する。', verbose_name='給与計算用 合計（表示）'),
        ),
    ]
