# Generated by Django 4.2.11 on 2025-12-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0011_driverdailyreport_payroll_bd_advance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreport',
            name='payroll_bd_advance',
            field=models.IntegerField(blank=True, default=0, help_text='立替返還（内訳）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='payroll_bd_etc_refund',
            field=models.IntegerField(blank=True, default=0, help_text='ETC返還（内訳）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='payroll_bd_over_short_to_company',
            field=models.IntegerField(blank=True, default=0, help_text='過不足（運転手→会社）（給与に含めない/参考）（内訳）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='payroll_bd_over_short_to_driver',
            field=models.IntegerField(blank=True, default=0, help_text='精算補填（会社→運転手）（内訳）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='payroll_bd_sales',
            field=models.IntegerField(blank=True, default=0, help_text='売上（内訳）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='payroll_total',
            field=models.IntegerField(blank=True, default=0, help_text='編集画面で算出した給与合計（表示専用）'),
        ),
    ]
