# Generated by Django 5.1.2 on 2025-07-23 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0011_driverdailyreportitem_combined_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dailyreports', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
