# Generated by Django 5.1.2 on 2025-07-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0012_driverdailyreport_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='charter_fee',
            field=models.PositiveIntegerField(blank=True, help_text='乘客支付的包车费用', null=True, verbose_name='貸切金額（円）'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='charter_payment_method',
            field=models.CharField(blank=True, choices=[('cash', '现金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他'), ('charter_cash', '貸切（現金）'), ('charter_bank', '貸切（振込）')], help_text='貸切付款方式，如 現金、振込、クレジットカード 等', max_length=20, null=True, verbose_name='貸切 支払方法'),
        ),
    ]
