# Generated by Django 4.2.11 on 2026-01-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0012_alter_driverdailyreport_payroll_bd_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreport',
            name='fuel_amount',
            field=models.PositiveIntegerField(default=0, help_text='給油に使用した金額。過不足判定から除外するための基準値。', verbose_name='給油金額（円）'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='fuel_paid_by',
            field=models.CharField(blank=True, choices=[('company_cash', '会社支払（売上現金/ながしで給油）'), ('driver', '運転手立替（後で会社→運転手で返還）')], default='company_cash', max_length=20, verbose_name='給油負担区分'),
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='payroll_bd_fuel_refund',
            field=models.IntegerField(blank=True, default=0, help_text='給油返還（会社→運転手）（内訳・月次集計用）'),
        ),
    ]
