# Generated by Django 5.1.2 on 2025-07-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0013_driverdailyreport_charter_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='charter_payment_method',
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='charter_fee',
            field=models.PositiveIntegerField(blank=True, help_text='银行振込の貸切金额', null=True, verbose_name='貸切金額'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_payment_method',
            field=models.CharField(blank=True, choices=[('cash', '现金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他')], max_length=20, null=True, verbose_name='ETC收取方式'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '现金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他')], max_length=16, verbose_name='支付方式'),
        ),
    ]
