# Generated by Django 5.1.2 on 2025-07-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0014_remove_driverdailyreport_charter_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreport',
            name='created_by',
        ),
        migrations.AddField(
            model_name='driverdailyreport',
            name='charter_payment_method',
            field=models.CharField(blank=True, choices=[('cash', '现金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他'), ('charter_cash', '貸切（現金）'), ('charter_bank', '貸切（振込）')], max_length=20, null=True, verbose_name='貸切 支払方式'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='charter_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='貸切金額（円）'),
        ),
        migrations.AlterField(
            model_name='driverdailyreport',
            name='etc_payment_method',
            field=models.CharField(blank=True, choices=[('cash', '现金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他'), ('charter_cash', '貸切（現金）'), ('charter_bank', '貸切（振込）')], max_length=20, null=True, verbose_name='ETC收取方式'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '现金'), ('uber', 'Uber'), ('didi', 'Didi'), ('credit', 'クレジットカード'), ('qr', 'バーコード(PayPay、auPay、wechat)'), ('kyokushin', '京交信'), ('omron', 'オムロン（愛のタクシーチケット）'), ('kyotoshi', '京都市他'), ('charter_cash', '貸切（現金）'), ('charter_bank', '貸切（振込）')], max_length=16, verbose_name='支付方式'),
        ),
    ]
