# Generated by Django 5.1.2 on 2025-08-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0017_remove_driverdailyreportitem_charter_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='is_charter',
        ),
    ]
