# Generated by Django 5.1.2 on 2025-08-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0018_remove_driverdailyreportitem_is_charter'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='包車金額'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_handling',
            field=models.CharField(blank=True, choices=[('normal_flow', '正常入金流程'), ('company', '公司处理'), ('boss', '老板收款'), ('driver', '司机自收')], default='normal_flow', max_length=20, null=True, verbose_name='包車處理方式'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_payment_channel',
            field=models.CharField(blank=True, choices=[('cash', '現金'), ('bank', '銀行轉帳'), ('wechat', '微信支付'), ('alipay', '支付寶'), ('other', '其他')], max_length=20, null=True, verbose_name='收款方式'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_remarks',
            field=models.CharField(blank=True, max_length=100, verbose_name='包車備註'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='is_charter',
            field=models.BooleanField(default=False, verbose_name='是否为包車'),
        ),
    ]
