# Generated by Django 5.1.2 on 2025-08-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0019_driverdailyreportitem_charter_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='charter_remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='包車備註'),
        ),
    ]
