# Generated by Django 5.1.2 on 2025-08-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0020_alter_driverdailyreportitem_charter_remarks'),
    ]

    operations = [
    ]
