# Generated by Django 5.1.2 on 2025-08-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0021_remove_charter_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='is_charter',
        ),
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='charter_fee',
        ),
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='charter_handling',
        ),
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='charter_payment_channel',
        ),
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='charter_remarks',
        ),
    ]
