# Generated by Django 5.1.2 on 2025-08-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0022_remove_charter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='包車金額'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_handling',
            field=models.CharField(blank=True, choices=[('normal_flow', '通常の入金処理'), ('boss', '老板处理'), ('driver', '司机留存'), ('other', '其他')], max_length=20, null=True, verbose_name='包車処理方式'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_payment_channel',
            field=models.CharField(blank=True, choices=[('cash', '現金'), ('bank', '銀行振込'), ('wechat', '微信'), ('alipay', '支付宝'), ('other', '其他')], max_length=20, null=True, verbose_name='包車収款方法'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='包車備考'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='is_charter',
            field=models.BooleanField(default=False, verbose_name='包車'),
        ),
    ]
