# Generated by Django 5.1.2 on 2025-08-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0023_add_charter_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='charter_fee',
        ),
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='charter_handling',
        ),
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='charter_payment_channel',
        ),
        migrations.RemoveField(
            model_name='driverdailyreportitem',
            name='charter_remarks',
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_amount_jpy',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='貸切日元金额'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_amount_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='貸切原始金额（元/円）'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='換算汇率'),
        ),
        migrations.AddField(
            model_name='driverdailyreportitem',
            name='charter_payment_method',
            field=models.CharField(blank=True, choices=[('self_wechat', '司机微信/支付宝'), ('rmb_cash', '人民币现金'), ('jpy_cash', '日元现金'), ('to_company', '转付公司'), ('boss_wechat', '老板微信'), ('bank_transfer', '银行转账')], max_length=20, null=True, verbose_name='貸切收款方式'),
        ),
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='is_charter',
            field=models.BooleanField(default=False),
        ),
    ]
