# Generated by Django 5.1.2 on 2025-08-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0024_remove_driverdailyreportitem_charter_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyreportitem',
            name='charter_payment_method',
            field=models.CharField(blank=True, choices=[('self_wechat', '司机微信/支付宝'), ('rmb_cash', '人民币现金'), ('jpy_cash', '日元现金'), ('to_company', '转付公司'), ('boss_wechat', '老板微信'), ('bank_transfer', '银行转账')], default='jpy_cash', max_length=20, null=True, verbose_name='貸切收款方式'),
        ),
    ]
