# Generated by Django 4.2.11 on 2025-08-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='车辆名称')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='型号')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='出厂年份')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='登録番号')),
                ('first_registration_date', models.DateField(blank=True, null=True, verbose_name='初度登録年月')),
                ('model_code', models.CharField(blank=True, max_length=50, verbose_name='型式')),
                ('engine_model', models.CharField(blank=True, max_length=50, verbose_name='原动机型号')),
                ('engine_displacement', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='总排气量（L）')),
                ('chassis_number', models.CharField(blank=True, max_length=50, verbose_name='车台番号')),
                ('length', models.PositiveIntegerField(blank=True, null=True, verbose_name='长度（mm）')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度（mm）')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度（mm）')),
                ('vehicle_weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='车重（kg）')),
                ('gross_weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='总重（kg）')),
                ('max_load_weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大積載量（kg）')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='乗車定員（人）')),
                ('usage', models.CharField(blank=True, max_length=50, verbose_name='用途')),
                ('body_shape', models.CharField(blank=True, max_length=50, verbose_name='车体形状')),
                ('user_company_name', models.CharField(blank=True, max_length=100, verbose_name='使用者名称')),
                ('owner_company_name', models.CharField(blank=True, max_length=100, verbose_name='所有者名称')),
                ('status', models.CharField(choices=[('usable', '使用可'), ('repair', '维修中'), ('retired', '已报废')], default='usable', max_length=20, verbose_name='车辆状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_reserved_only_by_admin', models.BooleanField(default=False, verbose_name='是否为调配用车（禁止普通用户预约）')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='当前里程（km）')),
                ('fuel_type', models.CharField(blank=True, max_length=20, verbose_name='燃料类型')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='车身颜色')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='车检到期日')),
                ('insurance_certificate_number', models.CharField(blank=True, max_length=50, verbose_name='保険証明書番号')),
                ('insurance_company', models.CharField(blank=True, max_length=100, verbose_name='保険会社')),
                ('insurance_start_date', models.DateField(blank=True, null=True, verbose_name='保険开始日')),
                ('insurance_end_date', models.DateField(blank=True, null=True, verbose_name='保険结束日')),
                ('insurance_status', models.CharField(blank=True, choices=[('valid', '加入中'), ('expired', '已过期'), ('none', '未加入')], default='valid', max_length=20, verbose_name='保険加入状況')),
                ('has_etc', models.CharField(choices=[('yes', '有'), ('no', '無'), ('self', '自備')], default='no', max_length=10, verbose_name='ETC状态')),
                ('has_oil_card', models.CharField(choices=[('yes', '有'), ('no', '無'), ('self', '自備')], default='no', max_length=10, verbose_name='油卡状态')),
                ('has_terminal', models.CharField(choices=[('yes', '有'), ('no', '無')], default='no', max_length=10, verbose_name='刷卡机状态')),
                ('has_didi', models.CharField(choices=[('yes', '有'), ('no', '無'), ('self', '自備')], default='no', max_length=10, verbose_name='Didi状态')),
                ('has_uber', models.CharField(choices=[('yes', '有'), ('no', '無'), ('self', '自備')], default='no', max_length=10, verbose_name='Uber状态')),
                ('can_enter_hachioji', models.BooleanField(default=False, verbose_name='可进入八条口')),
                ('etc_device', models.CharField(blank=True, max_length=50, verbose_name='ETC设备编号')),
                ('fuel_card_number', models.CharField(blank=True, max_length=50, verbose_name='油卡号')),
                ('pos_terminal_id', models.CharField(blank=True, max_length=50, verbose_name='刷卡机编号')),
                ('gps_device_id', models.CharField(blank=True, max_length=50, verbose_name='GPS设备编号')),
                ('department', models.CharField(blank=True, default='未指定', max_length=50, verbose_name='所属部门')),
                ('manager_name', models.CharField(blank=True, max_length=50, verbose_name='负责人姓名')),
                ('manager_phone', models.CharField(blank=True, max_length=30, verbose_name='负责人电话')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='车辆照片')),
            ],
        ),
    ]
