# Generated by Django 5.1.2 on 2025-06-11 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='车辆名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('repair', '维修中'), ('retired', '已报废')], default='available', max_length=20, verbose_name='车辆状态'),
        ),
    ]
