# Generated by Django 4.2.11 on 2025-08-29 18:22

import carinfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=carinfo.models.car_main_photo_path),
        ),
    ]
