# Generated by Django 5.1.2 on 2025-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0002_car_name_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='车身颜色'),
        ),
        migrations.AddField(
            model_name='car',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='car',
            name='etc_device',
            field=models.CharField(blank=True, max_length=50, verbose_name='ETC设备编号'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_card_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='油卡号'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='燃料类型'),
        ),
        migrations.AddField(
            model_name='car',
            name='gps_device_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='GPS设备编号'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='车辆照片'),
        ),
        migrations.AddField(
            model_name='car',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='车检到期日'),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='保险到期日'),
        ),
        migrations.AddField(
            model_name='car',
            name='manager_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='负责人姓名'),
        ),
        migrations.AddField(
            model_name='car',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='负责人电话'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='当前里程（km）'),
        ),
        migrations.AddField(
            model_name='car',
            name='pos_terminal_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='刷卡机编号'),
        ),
    ]
