# Generated by Django 4.2.11 on 2025-09-30 00:34

import carinfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0002_car_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=carinfo.models.car_main_photo_path, verbose_name='车辆照片'),
        ),
    ]
