# Generated by Django 4.2.11 on 2025-11-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0003_alter_car_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tenken_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='点检予定日'),
        ),
    ]
