# Generated by Django 5.1.2 on 2025-07-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0004_car_engine_displacement_car_first_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_shape',
            field=models.CharField(blank=True, max_length=50, verbose_name='车体形状'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='原动机型号'),
        ),
        migrations.AddField(
            model_name='car',
            name='first_registration',
            field=models.DateField(blank=True, null=True, verbose_name='初度登録年月'),
        ),
        migrations.AddField(
            model_name='car',
            name='gross_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='总重（kg）'),
        ),
        migrations.AddField(
            model_name='car',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='高度（mm）'),
        ),
        migrations.AddField(
            model_name='car',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='长度（mm）'),
        ),
        migrations.AddField(
            model_name='car',
            name='usage',
            field=models.CharField(blank=True, max_length=50, verbose_name='用途'),
        ),
        migrations.AddField(
            model_name='car',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度（mm）'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_displacement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='总排气量（L）'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='登録番号'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='车重（kg）'),
        ),
    ]
