# Generated by Django 5.1.2 on 2025-07-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0005_car_body_shape_car_car_type_code_car_engine_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='乗車定員（人）'),
        ),
        migrations.AddField(
            model_name='car',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='車台番号'),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_certificate_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='保険証明書番号'),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='保険会社'),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='保険終了日'),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='保険開始日'),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_status',
            field=models.CharField(blank=True, choices=[('valid', '加入中'), ('expired', '已过期'), ('none', '未加入')], default='valid', max_length=20, verbose_name='保険加入状況'),
        ),
        migrations.AddField(
            model_name='car',
            name='max_load_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='最大積載量（kg）'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner_company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='所有者名称'),
        ),
        migrations.AddField(
            model_name='car',
            name='user_company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='使用者名称'),
        ),
    ]
