# Generated by Django 5.1.2 on 2025-07-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0007_remove_car_car_type_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_reserved_only_by_admin',
            field=models.BooleanField(default=False, verbose_name='是否为调配用车（禁止普通用户预约）'),
        ),
    ]
