# Generated by Django 5.1.2 on 2025-07-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0008_car_is_reserved_only_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='can_enter_hachioji',
            field=models.BooleanField(default=False, verbose_name='可进入八条口'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_didi',
            field=models.CharField(choices=[('yes', '有'), ('no', '無')], default='no', max_length=10, verbose_name='Didi状态'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_etc',
            field=models.CharField(choices=[('yes', '有'), ('no', '無'), ('self', '自備')], default='no', max_length=10, verbose_name='ETC状态'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_oil_card',
            field=models.CharField(choices=[('yes', '有'), ('no', '無'), ('self', '自備')], default='no', max_length=10, verbose_name='油卡状态'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_terminal',
            field=models.CharField(choices=[('yes', '有'), ('no', '無'), ('self', '自備')], default='no', max_length=10, verbose_name='刷卡机状态'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_uber',
            field=models.CharField(choices=[('yes', '有'), ('no', '無')], default='no', max_length=10, verbose_name='Uber状态'),
        ),
    ]
