# Generated by Django 5.1.2 on 2025-08-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0009_car_can_enter_hachioji_car_has_didi_car_has_etc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='has_didi',
            field=models.CharField(choices=[('yes', '有'), ('no', '無'), ('self', '自備')], default='no', max_length=10, verbose_name='Didi状态'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_terminal',
            field=models.CharField(choices=[('yes', '有'), ('no', '無')], default='no', max_length=10, verbose_name='刷卡机状态'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_uber',
            field=models.CharField(choices=[('yes', '有'), ('no', '無'), ('self', '自備')], default='no', max_length=10, verbose_name='Uber状态'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('usable', '使用可'), ('repair', '维修中'), ('retired', '已报废')], default='usable', max_length=20, verbose_name='车辆状态'),
        ),
    ]
